[package]
name = "wallet"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
web3 = { version = "0.18.0", default-features = false, features = ["signing"] }
hex = "0.4"
anyhow = "1.0"
