[package]
name = "wallet"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
ethers = "1.0.2"
anyhow = "1.0"